language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: BWC9t6AzhHusdCQwEoQ/3CkdBw60CeZTR34ixUwVEV2SesFrXoK5JiOWZ697/rgYxgR84DHm9pbhicu+f+8UGD6etVyWnraetvPAS0uXFWp/PtbiJ7KULd6bOz61LM2A1sci+u2UjVXP6I0P6ECKm1/5nhM1UBbWh1f1osgldSYHnl1Y1nEyi13JZd7ghbG4BegMramzitOeE4LVPrMALr5A4FZrLaF9mV3J80Duw8L5matxhctACfF3JWl/x9ugFhiOqt+xl4jv2r5Bl4ZOk2FbUuHx9kWl3YK/N2Dtb5ALcMh1ZF02CxwFuF7d4M+w95CuWcMCNYbcjN6pqELU2ySMZWZMttYdSgMb1RuUuF1xamobpm5mBN5elj3xb3Y0jKQAWS9wZRw6POG93EpOipLJmmLxv3tdt0M8hIP2Oa6jNIDBlwstbb2y2VOikR7ODGBv4RJWHln+Kfpn2+nmXZV7T1McsKlp7FK5CIPqSjdx28Yq3bXelazkAne86h6MIFNGrZXIzQYT+Mc0rEVsJjxW0MlzbwF9eaMupCDwifa5ZQZwu6ua6ldoIWt95KlFv8dM8v1GyLchAlbcpj6nvEaYyFChkvngowPg4eULyqHBqrPByo5heP5PHcl4/F87aa3aZoG4vq9z2+PvKuX9XuNQRW7XJqqWERzzruyWlV0=
  app: pure-plateau-69872
  on:
    repo: condericson/node-restaurants-app-mongoose-with-tests
