language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: ZCcWQD2hkC65soq4cn9IyxEAujy5CiXOAfgoRkhXjx8MG3Pm3FVko8rg1xSVkLHsKhh2T1CwYDZnTv7cELJpL994Q5cwNlsxJaoK/CiHfjaArlmqPBnrFaro8dVohVXGOBby5vW83UvBSZfNhvUmeuVyWenaC9+48IgL/hGuF/Ga/X+ZfvSWdFETWUcYzQA3zqENQaEAOYioJkoKrtU9WzwjgWt21AFMbBp9E6TrdhaXyhhWSBEg7QZnF5jdgKKdo/GlAjNO0vHhzNQCIMs0dbQlIk2t+sUqQp3g1mLYgYTKrKJbf4wRP0eDSLiOOJaCN57jJZIY2Q0L8hr2WwZ0sRXxtz2BEZ64RyGU4XvGbO4Mz4BNlK8ID2gGRYWuelp+/j32bQII/rgvtrlxZiPfpmok5+3shreTpWAM/bHSD2SXyMtlrA88o0tI9nkWQgIbqpo7kO0VdVvyWX8hopDDjJw+EagTVYctH/dhowvL1Fm0Gg+p/iih9PXec6jL67cTtdHZ/gGxJMoYUa1GiH6W80NhvKpxCXZ1VZdP/QOA2h19Yj/RYyPk1KHwxxcK0zYpPOCib6w1CHYYNgdY89QZTv2eGH34PtJqRnfme8pC7Mkat7iW06UFktrmqNTEqygxVYrIX6RgeYfw10MI2+jg+gaIWarSV+CAjhlvS4VJV98=
  app: pure-plateau-69872
  on:
    repo: condericson/node-restaurants-app-mongoose-with-tests
